
# Задача 1. «Треугольник с максимальным периметром»
### Массив A состоит из целых положительных чисел ­ длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью ­ функция возвращает 0.

In [1]:
#Находжение периметра
def Perimetr (a, b, c):
    if (a+b)>c and (a+c)>b and (b+c)>a:
        return int(a+b+c)
    else:
        return 0
#
length=int(input('Введите длину массива'))
mas=[]
for i in range(length):
    mas.append(int(input()))
mas=sorted(mas, reverse=True)
print(mas)
for i in range(len(mas)-2):
    if Perimetr(mas[i], mas[i+1], mas[i+2])>0:
        print("Периметр=", Perimetr(mas[i], mas[i+1], mas[i+2]))
        break

Введите длину массива 7
 1
 3
 4
 6
 8
 9
 10


[10, 9, 8, 6, 4, 3, 1]
Периметр= 27


# Задача 2. «Максимальное число»
### Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число.

In [2]:
class maxs:
    def per_mas(n, m, r):
        for i in range(n):
            for j in range(r, m):
                yield i, j
                
    def maxel(nums):
        rez=""
        for i in range(len(nums)):
            for j in range(i+1, len(nums)):
                if int(nums[j][0])>int(nums[i][0]):
                    nums[j], nums[i]=nums[i], nums[j]
                elif (int(nums[j][0])==int(nums[i][0])):
                    r=1
                    while len(nums[j])>r and len(nums[i])>r and int(nums[j][r])==int(nums[i][r]):
                        r=r+1
                    for k, m in per_mas(len(nums[j]), len(nums[i]), r):
                        #print(nums[j][k], "and", nums[i][m])
                        if int(nums[j][k])>int(nums[i][m]):
                            nums[j], nums[i]=nums[i], nums[j]
                            break
                        
        for i in range(len(nums)):
            rez=rez+" "+str(nums[i])
        return rez

length=int(input('Введите длину массива'))
nums=[]
for i in range(length):
    nums.append(input())
print(maxs.maxel(nums))

Введите длину массива 5
 1
 3
 5
 7
 9


 9 7 5 3 1


In [5]:
def check(a,b):
    one=str(a)+str(b)
    two=str(b)+str(a)
    if int(one)>int(two):
        return True
    else:
        return False
    
def shell(massline):
    length=len(massline)
    l=length
    while l>0:
        for i in range(length-l):
            j=i
            while j>=0 and check(massline[j+l], massline[j]):
                massline[j], massline[j+l]=massline[j+l], massline[j]
                j=j-l
        l=int(l/2)
    strr=""
    for i in range(len(massline)):
        strr=strr+" "+str(massline[i])
    return strr

mas1=[701,702,703]
mas2=[777772,5]
mas3=[2,27,38,5,12]
print(shell(mas1))
print(shell(mas2))
print(shell(mas3))

 703 702 701
 777772 5
 5 38 27 2 12


# Задача 3. «Сортировка диагоналей в матрице»
### Дана матрица mat размером m * n, значения ­ целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [7]:
import numpy
def per_mas(n, m):
    for i in range(n):
        for j in range(m):
            yield i, j
m, n= map(int, input('Введите m и n:').split(' '))
massiv = numpy.random.random_integers(0, 20, size=(m, n))
print(massiv)
for i, j in per_mas(len(massiv[0]), len(massiv)):
    k=j
    l=i
    while k<len(massiv[0]) and l<len(massiv):
        if massiv[i][j]>massiv[l][k]:
            massiv[i][j], massiv[l][k]=massiv[l][k], massiv[i][j]
        k=k+1
        l=l+1
            
print("\n\n")
print(massiv)

Введите m и n: 5 5


[[18  3  2 17  3]
 [ 0 16  8 18 17]
 [11  4 10  0  7]
 [18  5  3 19 12]
 [18  2 20 14  5]]



[[ 5  0  2 17  3]
 [ 0 10  3  7 17]
 [ 5  3 16  8 18]
 [ 2 11  4 18 12]
 [18 18 20 14 19]]


/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:7: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  import sys
